### ISSUE TITLE
Need precision about gitlab ci and project naming and license consumption

### ISSUE THREAD

**Issue by florentulve** [checkmarx-ltd/cx-flow#1282]
Hi 

I've integrated the default gitlab ci template in my project (https://github.com/checkmarx-ltd/cx-flow/blob/develop/templates/gitlab/v3/Checkmarx.gitlab-ci.yml).

I have a branch develop and feature branch under a merge request.

The default gitlab ci template hase created two project:
-  A myrepo-develop project 
-  A myrepo-feature-branch.

So I was wondering if it is this normal and if this two project consumes two licenses ?

I've read the wiki but it is a bit overwhelhming there's a lot of settings and it's not clear.

![image](https://github.com/checkmarx-ltd/cx-flow/assets/2817358/99ecc6ae-5943-45a2-b53a-f1e01bd0a5af)

**Comment by aine-rb** [comment]
Hi,

I'm updating this post because the subject interests me too.

Unless I'm mistaken, by default a new CxSAST project will be created for each combination of "$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME" via the GitLab CI template integration.
This implies consuming a new CxSAST project license each time.

However, the "cx-branch" parameter proposed by CxFlow allows you to create a branch on CxSAST rather than a project, which avoids using a CxSAST project license.
The default value for this parameter is "false".

My question for the Checkmarx team: Is it possible to add this parameter to the GitLab CI template so that it is taken into account by the CxFlow client?
For example, with :
`CHECKMARX_CX_BRANCH : "true"`

**Comment by satyamchaurasiapersistent** [comment]
Fixed in Release 1.7.04
