### ISSUE TITLE
Add Support for Project Branching in Checkmarx

### ISSUE THREAD

**Issue by kmcdon83** [checkmarx-ltd/cx-flow#153]
Introduce Checkmarx Project Branching capability within CxFlow

Currently, a new project is created for every repo/branch combination unless project naming overrides are leveraged. This Enhancement is to leverage a base project and branch it within Checkmarx instead of creating new each time.

Issue link from previous repo: https://github.com/checkmarx-ts/cx-flow/issues/31

**Comment by MithileshPawar** [comment]
This needs to be investigated. Understanding the relationship between the base project and the current branch given a webhook event is the problem to solve.

**Comment by MithileshPawar** [comment]
In the standard configuration, without branching support, scalability of CxFlow is seriously impacted since Checkmarx will quickly become cluttered with projects generated from PR scans which a.) each unnecessarily consume a license b.) are almost certain to be irrelevant as soon as the PR is merged/closed, since they are named for the branch to merge instead of the base branch. To prevent rapidly consuming all available licenses and cluttering the Checkmarx server with irrelevant projects for one-off PR scans, CxFlow users must implement some method for automated identification and deletion of these PR projects.

As a partial mitigation, we were able to use the groovy project script to detect if a received GitHub webhook represented a PR event, and, if so, use the source project name suffixed with " PR" so that all PR scans for a base branch would go to a corresponding PR project. Then, we pre-create the PR projects when repositories are initially onboarded using our own CLI tool, so that we can create these PR projects by branching the source project, instead of consuming an extra license.

I took a look at the source for CxFlow and the SDK to see if we could easily fix the issue, but it doesn't look like SDK even has a method to support branching (or at least not an obvious method for the version of the SDK used by CxFlow). On a related note - but outside the scope of the SDK or CxFlow - I find it incredibly frustrating that there is no API endpoint available for either the REST, OData, or SOAP APIs that allow you to determine if a particular project is a "branched" project or not, or what branched projects exist (if any) for a given "source" project. I had to resort to querying the database directly, which I also noticed doesn't seem to cleanup broken source project -> branched project mappings, since there were entries which referred to branched projects which had been deleted. So any heavy use of branching seems like that table will just grow forever until it the DB runs out of space.

**Comment by GeekMasher** [comment]
@MithileshPawar There is a REST API call in 8.8+ versions of Checkmarx which you supply the ID of the base project (`master` or `develop` project) and it will (after X seconds) will create a branched project.

Maybe the SDK doesn't have this call built in to it but it is possible (used it in the past but I don't know if there are limitations).

https://checkmarx.atlassian.net/wiki/spaces/KC/pages/595492865/Create+Branched+Project+-+POST+projects+id+branch+v8.8.0+and+up

Hope this helps.

**Comment by kmcdon83** [comment]
@GeekMasher there are serious implications to branching.  Feel free to reach out and we can discuss the use case.  There are many challenges which have held us back form implementing.  Things like, what if the base branch was never scanned?  What about branches 4 layers deep (master->develop->release->feature), which should be the base?  This is typically only asked for to alleviate licensing concerns instead of actual technical capability which I believe should drive a licensing conversation instead of trying to introduce extra unnecessary complexity.  The fact that triaged results are maintained across projects within a team (false positives for example), make the branching not add any additional value.

**Comment by jbrotsos** [comment]
Branching is now supported
