### ISSUE TITLE
CxFlow breaks custom project configuration in CxSAST

### ISSUE THREAD

**Issue by jbruinaud** [checkmarx-ltd/cx-flow#459]
### Description

If you have a project with a specific configuration (scheduled scan with Git location, pre/post-scan emails, post-scan actions), launching a CxFlow scan on this project removes all pre/post-scan settings and switches the location to local thus preventing future CxSAST-scheduled scans to run.

### Expected Behavior

CxFlow does not modify or restores the original project configuration after the scan is completed.

### Actual Behavior

Configuration example before the CxFlow scan:

![image](https://user-images.githubusercontent.com/45826216/95896046-9238b980-0d83-11eb-992f-dc965fad5ec6.png)
![image](https://user-images.githubusercontent.com/45826216/95896049-9533aa00-0d83-11eb-82cd-a7ef7e0f8bd1.png)
![image](https://user-images.githubusercontent.com/45826216/95896052-97960400-0d83-11eb-80fb-b263f2cefac2.png)

Project configuration after the CxFlow scan:

![image](https://user-images.githubusercontent.com/45826216/95896133-b2687880-0d83-11eb-86e8-80ba1c323212.png)
![image](https://user-images.githubusercontent.com/45826216/95896149-b5fbff80-0d83-11eb-9c70-147440c896bf.png)
![image](https://user-images.githubusercontent.com/45826216/95896156-b85e5980-0d83-11eb-9a9d-7981a944b2fd.png)

### Reproduction

- Create a project in CxSAST
- Go to Projects & Scans > Projects and create a custom configuration:
  - Configure the project with a Git location (Location tab)
  - Configure a scan schedule (Scheduling tab)
  - Configure pre/post-scan emails/action (Advanced tab)
- Launch a scan with CxFlow, e.g: java -jar cx-flow-1.6.9.jar --spring.config.location=cxflow-batch-JIRA.yml --scan --f="DSVW-master" --cx-team="/CxServer" --cx-project="DSVW-GitHub-action" --app="POC" --branch="master" --repo-name="DSVW" --namespace="POC"
- When the scan is executed, look at the configuration again

### Environment Details

Issue reproduced on CxSAST 9.2.0 with CxFlow batch 1.6.9 and CxFlow GitHub Action.

**Comment by milo-minderbinder** [comment]
@jbruinaud @AvivCx this also occurs when running CxFlow in web mode, and is particularly problematic when using GitHub App based integration, because CxFlow will overwrite Checkmarx project source settings, including overwriting any previously configured git repo URL/credentials and setting it to the HTTPS clone URL with the username in the userinfo part set to x-access-token and the password set to the GitHub app’s installation access token. This doesn’t really make any sense if there are existing, working source settings configured, since GitHub app access tokens are only valid for an hour at most. Once the hour has gone by, if the initial scan is still waiting to be queued, or if a user wants to initiate a new scan from the Checkmarx web portal, then the scan will fail to start due failure when cloning repo with the now expired credentials.

FYI, not sure if the apparent suggestion/fix to disable the scan options override parameter in the linked PR was supposed to address this case, but it does not, at least in my testing with the latest CxFlow release.

**Comment by kmcdon83** [comment]
@milo-minderbinder , I am fine with adding another flag for excluding updates to the git url with the token, but what about when a PR is submitted (new PR), and we create the project with the github app token, and then an hour later an update to the PR branch occurs, and since we aren't updating the token (which lives 10 minutes) , your existing project clone will fail due to the token expiring.  What you describe works for anything you added with a previous long living PAT.  I just want to make sure this would meet the intent.

**Comment by milo-minderbinder** [comment]
@kmcdon83 yep agreed that would definitely be an issue, and it’s why I specified that source config should only be preserved if it is an “existing, _working_” config (emphasis added — sorry, should have made that more clear originally). I realize this is a difficult feature request to implement well, since the CxSAST APIs only provide limited visibility into the existing project source config (redacts credentials in repo URL, does not provide access to private or public SSH key or key hash/ID for repos where one is configured, and doesn’t expose a “test connection” endpoint except through SOAP Portal SDK IIRC), desired behavior may vary depending on context and require more nuanced logic than a simple feature flag would afford, etc.. 

My first thoughts were to add an option to CxFlow config that accepts a list of supported authentication methods/ credential types, ordered in terms of desired precedence. For example types might be `token`, `app`, `ssh`, `existing`, and `script`, where `existing` would signify that the authN method already in place should be used if project and source settings already exist and fall back to standard config behavior otherwise, and `script` would signify that source settings should be set dynamically by passing the scan request to a groovy script (like team/project name script option) and returning parsed output. So, for example, option value in YAML might be:
```yaml
auth-config-precedence:
  - ssh
  - token
  - existing
  - app
  - script
```
In that case, when push event is received, then:
* if the Checkmarx project already exists, then retrieve existing source settings and:
    * if ssh key is set (highest precedence), then don’t change. Otherwise,
    * if CxFlow properties have (personal access) token defined, overwrite source settings with HTTP url with token, otherwise,
    * try to use whatever authN mechanism is already in place and update/refresh creds where relevant (eg, if source settings only has redacted username but no redacted password indicating token is used, then update source settings with token if configured in properties; if redacted username and password present and GitHub app settings are defined, fetch a new installation access token for the repo and update source settings), otherwise, if existing source settings don’t have required corresponding config options defined in CxFlow (eg existing settings use token but no token is defined in CxFlow properties), then
    * if GitHub app settings defined in CxFlow, fetch installation access token and set source settings to HTTP url with token user and password
* if Checkmarx project doesn’t exist:
  * ssh key isn’t supported in CxFlow (yet) so,
  * if token is defined in CxFlow properties, then set source settings to HTTP url with token authN, otherwise,
  * since no project or source settings exist, then
    * if GitHub app config is defined, set source settings accordingly, otherwise,
    * if source settings script exists, execute it with scan config as input and parse source settings from output and set them In Checkmarx, otherwise if no script exists, it throws exception, or output parsing fails, then
    * no other options are available so bubble up exception

**Comment by kmcdon83** [comment]
@milo-minderbinder I understand the ask here.  Let me take it with the team to discuss.

**Comment by AvivCx** [comment]
Hey @MithileshPawar .
can you please update what has changed here in the latest version? I would like to close this issue 
Thanks

**Comment by MithileshPawar** [comment]
Hi, so there is a new change that has been made which will fix this bug partially. It works like this -
1) Like the previous behavior, CxFlow checks if the project already exists in SAST.
2) If the project exists, Cxflow will try to fetch the remote settings for this project and check if the ssh key is already configured.
  a) If the ssh key is already configured, cxflow will skip updating the project's remote settings/git url.
  b) If the ssh key is not present, cxflow will update the project's remote settings/git url.

This change will also help in preserving the scheduled scan settings for the project which has the SSH key configured.
