### ISSUE TITLE
Template path error running in docker container in gitlab pipeline

### ISSUE THREAD

**Issue by ahillmaniii** [checkmarx-ltd/cx-flow#503]
### Description

> Provide a description of the issue
We are running a gitlab pipeline, using the cxflow docker image and we get an error about a template path within the cx-flow jar
2020-11-06 17:50:15.625 DEBUG 33 --- [           main] s.u.f.FreeMarkerConfigurationFactoryBean : Cannot resolve template loader path [classpath:/templates/] to [java.io.File]: using SpringTemplateLoader as fallback
java.io.FileNotFoundException: class path resource [templates/] cannot be resolved to absolute file path because it does not reside in the file system: jar:file:/app/cx-flow.jar!/BOOT-INF/classes!/templates/

### Expected Behavior
Expected run to complete successfully.
### Actual Behavior
Errors out before completion
### Reproduction

> Detail the steps taken to reproduce the issue
> 
> Where applicable, please include (exclude sensitive information):
>
> - Code of Files to reproduce the issue
> - Log files
> - Application settings
using this file as the template for gitlab pipeline:
https://gitlab.com/jbrotsos/checkmarx/-/blob/master/.checkmarx-template.yml

> - Screenshots

### Environment Details

> Provide any information relating to the environment the issue was identified in - include applicable version and additional runtime information (include OS or other underlying infrastructure)
Let me know if more info is required.

**Comment by jbrotsos** [comment]
Hello @ahillmaniii,

That template file is not officially supported and is just a file I was testing a template out with.

Did you follow our documentation at checkmarx.com/gitlab?

James

**Comment by ahillmaniii** [comment]
I'll go through the docs. Thanks.

**Comment by ahillmaniii** [comment]
@jbrotsos Secondary issue. We have our own certificate on our checkmarx server. The cx-flow app is having ssl errors when connecting. 

Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Unless I am mistaken we would need to create our own docker image containing the cx-flow app including a custom trust store with our certificate.

Is this correct? Any other options?

**Comment by jbrotsos** [comment]
@ahillmaniii 

As described in https://checkmarx.com/gitlab, please do the following

1. add an environment variable named LOCAL_CA_CERT that contains the cert
2. add the following lines in the .checkmarx.yml file as the first steps under 'script'

script:
   - cat ${LOCAL_CA_CERT} > localcert.cert
   - keytool -import -trustcacerts -alias localca -file localcert.cert –keystore /usr/local/share/ca-certificates/ -noprompt

If you have further questions, please reach out to me at james.brotsos@checkmarx.com or file a new issue that describes your problem.  I will update the documentation to add this cert info and close this one because you were using an unsupported template file.
