### ISSUE TITLE
Dashes replacing spaces in Project Names

### ISSUE THREAD

**Issue by jbrotsos** [checkmarx-ltd/cx-flow#534]
### Description

When using --cx-project="Project Name" flag to set the project with CxFlow, the "Project Name" value is taken from a Bitbucket repository variable. It appears that when having spaces in the project name, CxFlow automatically changes them to dashes (-). As a result, it was trying to find a project named "Project-Name" which does not exist, and thus it tries to create a new one, which creates a new project and consumes a license.

...
2020-11-18 08:14:06.977  INFO 1 --- [           main] c.c.s.s.CxService                         [d2YF7cqs] : Creating Project Project-Name for ownerId 7
2020-11-18 08:14:07.114 ERROR 1 --- [           main] c.c.s.s.CxService                         [d2YF7cqs] : HTTP error code 403 FORBIDDEN while creating project with name Project-Name under owner id 7
2020-11-18 08:14:07.117 ERROR 1 --- [           main] c.c.s.s.CxService                         [d2YF7cqs] : org.springframework.web.client.HttpClientErrorException$Forbidden: 403 Forbidden: [{
  "messageCode": 28501,
  "messageDetails": "Max. number of licensed projects is already utilized"
}]
...

Workaround was accomplished by renaming the projects in Checkmarx to have a dash instead of spaces.

### Expected Behavior

When using --cx-project, it should use spaces in the project name since CxSAST allows for project names with spaces in the name.

### Actual Behavior

It is creating a new project with a dash instead of spaces.

### Reproduction

Use a project name with spaces.

### Environment Details

Coming from Bitbucket but I suspect this would be across the board.

**Comment by kmcdon83** [comment]
@jbrotsos the project name has many downstream implications.  We have had the discussion around this previously.
Alphanumeric  _-. are acceptable as designed.

**Comment by kmcdon83** [comment]
I would also like to remove bug status since this is as-designed.  I am fine with it being listed as a feature.

**Comment by cx-scord** [comment]
Could this be enforced by the Project Groovy script?

Currently is not allowing to do that as the normalization occurs after the Groovy script executes, I would like to understand better what are the ramifications and what are the consequences since I could rebuild the code and add the '\s' to the [regular expression replacing the characters](https://github.com/checkmarx-ltd/cx-flow/blob/master/src/main/java/com/checkmarx/flow/service/ProjectNameGenerator.java#L69)

This has implications in the licensing model since the number of projects could reach the limit and one already has an existing project where they want the main branch (or any other protected branch) to be scanned into.

@kmcdon83 @AvivCx knowing those downstream shortcomings of changing this would be important to understand the impact if someone decides simply to add the space character to the exclusions and rebuild the code themselves, can you please advise?

**Comment by jbrotsos** [comment]
This has been fixed.
