### ISSUE TITLE
Token issue and a few questions

### ISSUE THREAD

**Issue by cpyburn** [checkmarx-ltd/cx-flow#544]
•	We have noticed an issue with the CxFlow, the token that is generated for the command line CxConsole tool is not valid for CxFlow.  It is expecting a username\password or a client secret.  There is not much information on how to generate a client secret.  I am assuming it is referring to the Token Based Authentication for the REST API (https://checkmarx.atlassian.net/wiki/spaces/KC/pages/202506366/Token-based+Authentication+v8.6.0+and+up), but I am worried that the token is short lived.  I am wondering if we need a service account for the CI\CD process.

•	For CxFlow GitHub Action, 
o	How do you set thresholds for failing the merge check in the GitHub PR Check?
o	How do you set the Inclusion and Exclusion list?

**Comment by AvivCx** [comment]
Hi @cpyburn 
I'll try to answer some of your questions here. if you have further question please consider work with checkmarx PS to get a closer look on your flow

1. when work with SAST 8.9, the client secret is hard coded and there is no option to generate your own client secret.
2. when work with SAST 9.0 you can generate token with some more advanced steps. you can follow this guide. actually it's more a SAST question rather than CxFlow - https://checkmarx.atlassian.net/wiki/spaces/KC/pages/1192264200/Create+New+OIDC+Client+-+POST+OIDCClients

3. setting thresholds for pull request feedback:  https://github.com/checkmarx-ltd/cx-flow/wiki/Thresholds-and-policies#thresholds-vs-basic-filters

4. Exclude files or folders, look for it here: https://github.com/checkmarx-ltd/cx-flow/wiki/Configuration

Thanks
