### ISSUE TITLE
Ability to run async scan that returns scan-id and then run the cxflow command later in pipeline and fetch/wait for results based on scanId

### ISSUE THREAD

**Issue by nirw** [checkmarx-ltd/cx-flow#969]
### Describe the problem

When a scan is triggered asynchronously from the pipeline we would like to have the scanId returned from CxFlow
Later in the pipeline triger CxFlow CLI to fetch the results based on a scanId into the relevant tracker, but in case the scan hasn't finished/still in the queue CxFlow should wait for the results till completed

### Proposed solution

 - introduce an option for CxFlow asynchronos scan to return scanId 
 - introduce an option for CxFlow CLI for retrieving scan results by Id (rather than latest) and wait until completed

### Additional details

> Add any other details / contexts / screenshots about the feature request.

**Comment by itsKedar** [comment]
Fixed in 1.6.37

For Async behavior bug-tracker can be set as NONE.

To fetch the results for specific scanId and provide feedback (defect / issue tracking) new CLI parameter is introduced for project Mode as --scanId 

eg :-java -jar cx-flow-<ver>.jar --project  --scanId=<unique scanId> --cx-team="CxServer/SP/Checkmarx/Test"  --cx-project="riches-main"  --app=AppName
